"""
Active Setup Monitor for Confluence X.

Monitors active setups for state changes, confirmation conditions,
and invalidation triggers.
"""
from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional

from ..setup.setup_lifecycle import SetupLifecycle, SetupRecord, SetupState

log = logging.getLogger(__name__)


@dataclass
class SetupAlert:
    """An alert generated by setup monitoring."""
    setup_id: str
    symbol: str
    alert_type: str  # 'approaching_entry', 'confirmation', 'invalidation', 'expiry'
    message: str
    timestamp: float = field(default_factory=time.time)
    metadata: dict = field(default_factory=dict)


@dataclass
class MonitoringState:
    """Monitoring state for a setup."""
    setup_id: str
    last_check: float = 0.0
    distance_to_entry: float = 0.0
    distance_to_stop: float = 0.0
    confirmation_conditions: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    is_active: bool = True


class SetupMonitor:
    """
    Active Setup Monitor.
    
    Monitors active setups for state changes, confirmation conditions,
    and invalidation triggers.
    """
    
    def __init__(self, setup_lifecycle: SetupLifecycle):
        self._setup_lifecycle = setup_lifecycle
        self._monitoring_state: Dict[str, MonitoringState] = {}
        self._callbacks: List[Callable] = []
    
    def register_callback(self, callback: Callable):
        """Register a callback for monitoring alerts."""
        self._callbacks.append(callback)
    
    def check_setup(self, setup_id: str, current_price: float) -> Optional[SetupAlert]:
        """Check a setup and generate alerts if needed."""
        setup = self._setup_lifecycle.get_setup(setup_id)
        if not setup:
            return None
        
        # Get or create monitoring state
        if setup_id not in self._monitoring_state:
            self._monitoring_state[setup_id] = MonitoringState(setup_id=setup_id)
        
        state = self._monitoring_state[setup_id]
        state.last_check = time.time()
        
        # Calculate distances
        if setup.entry_low > 0 and setup.entry_high > 0:
            entry_mid = (setup.entry_low + setup.entry_high) / 2
            state.distance_to_entry = abs(current_price - entry_mid) / entry_mid * 100
        
        if setup.stop_loss > 0:
            state.distance_to_stop = abs(current_price - setup.stop_loss) / setup.stop_loss * 100
        
        # Check for approaching entry
        if setup.state == SetupState.WATCH and state.distance_to_entry < 0.1:
            alert = SetupAlert(
                setup_id=setup_id,
                symbol=setup.symbol,
                alert_type='approaching_entry',
                message=f"{setup.symbol} approaching entry zone ({state.distance_to_entry:.2f}% away)",
                metadata={
                    'current_price': current_price,
                    'entry_low': setup.entry_low,
                    'entry_high': setup.entry_high,
                    'distance_pct': state.distance_to_entry,
                },
            )
            self._emit_alert(alert)
            return alert
        
        # Check for invalidation
        if setup.invalidation_price > 0:
            if setup.direction == 'BUY' and current_price < setup.invalidation_price:
                self._setup_lifecycle.transition(
                    setup_id, SetupState.INVALIDATED,
                    reason=f'Price {current_price} below invalidation {setup.invalidation_price}'
                )
                alert = SetupAlert(
                    setup_id=setup_id,
                    symbol=setup.symbol,
                    alert_type='invalidation',
                    message=f"{setup.symbol} setup invalidated - price below invalidation level",
                    metadata={
                        'current_price': current_price,
                        'invalidation_price': setup.invalidation_price,
                    },
                )
                self._emit_alert(alert)
                return alert
            
            if setup.direction == 'SELL' and current_price > setup.invalidation_price:
                self._setup_lifecycle.transition(
                    setup_id, SetupState.INVALIDATED,
                    reason=f'Price {current_price} above invalidation {setup.invalidation_price}'
                )
                alert = SetupAlert(
                    setup_id=setup_id,
                    symbol=setup.symbol,
                    alert_type='invalidation',
                    message=f"{setup.symbol} setup invalidated - price above invalidation level",
                    metadata={
                        'current_price': current_price,
                        'invalidation_price': setup.invalidation_price,
                    },
                )
                self._emit_alert(alert)
                return alert
        
        # Check for expiry
        if setup.expires_at and time.time() > setup.expires_at:
            self._setup_lifecycle.transition(
                setup_id, SetupState.EXPIRED,
                reason='Setup expired'
            )
            alert = SetupAlert(
                setup_id=setup_id,
                symbol=setup.symbol,
                alert_type='expiry',
                message=f"{setup.symbol} setup expired",
                metadata={'expires_at': setup.expires_at},
            )
            self._emit_alert(alert)
            return alert
        
        return None
    
    def check_all_active(self, price_getter: Callable[[str], float]) -> List[SetupAlert]:
        """Check all active setups and generate alerts."""
        alerts = []
        active_setups = self._setup_lifecycle.get_active_setups()
        
        for setup in active_setups:
            current_price = price_getter(setup.symbol)
            if current_price > 0:
                alert = self.check_setup(setup.setup_id, current_price)
                if alert:
                    alerts.append(alert)
        
        return alerts
    
    def get_monitoring_state(self, setup_id: str) -> Optional[MonitoringState]:
        """Get monitoring state for a setup."""
        return self._monitoring_state.get(setup_id)
    
    def cleanup(self, max_age_seconds: float = 86400):
        """Cleanup old monitoring state."""
        cutoff = time.time() - max_age_seconds
        old_ids = [
            sid for sid, state in self._monitoring_state.items()
            if state.last_check < cutoff
        ]
        for sid in old_ids:
            del self._monitoring_state[sid]
    
    def _emit_alert(self, alert: SetupAlert):
        """Emit alert to all callbacks."""
        for callback in self._callbacks:
            try:
                callback(alert)
            except Exception as e:
                log.error("Error in monitoring callback: %s", e)
