import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowRight, CalendarClock, FlaskConical, RefreshCw, ShieldAlert, TrendingDown, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import { bwtsApi, type CryptoAnalysis, type V2BacktestReport } from '../services/bwtsApi';

type PairRow = { pair: string; analysis?: CryptoAnalysis; loading: boolean; error?: string };
const planRank = (analysis?: CryptoAnalysis) => ({ STRONG: 5, VALID: 4, WATCHLIST: 3, WAIT: 2, BLOCKED: 1 }[analysis?.trade_plan?.status || ''] || 0);
const planStyle: Record<string, string> = {
  STRONG: 'border-emerald-400/30 bg-emerald-400/10 text-emerald-300', VALID: 'border-cyan-400/30 bg-cyan-400/10 text-cyan-300',
  WATCHLIST: 'border-amber-400/30 bg-amber-400/10 text-amber-300', WAIT: 'border-slate-400/20 bg-slate-400/10 text-slate-400',
  BLOCKED: 'border-rose-400/30 bg-rose-400/10 text-rose-300',
};

const LiveScanner: React.FC = () => {
  const [rows, setRows] = useState<PairRow[]>([]); const [refreshing, setRefreshing] = useState(false);
  const [lastUpdate, setLastUpdate] = useState<Date | null>(null); const [globalError, setGlobalError] = useState<string | null>(null);
  const [validation, setValidation] = useState<V2BacktestReport | null>(null); const [validating, setValidating] = useState(false); const [validationTimeframe, setValidationTimeframe] = useState('1h'); const [validationDepth, setValidationDepth] = useState(20000);
  const refreshInFlight = useRef(false);
  const refresh = async () => {
    if (refreshInFlight.current) return;
    refreshInFlight.current = true; setRefreshing(true); setGlobalError(null);
    try {
      const { pairs } = await bwtsApi.pairs(); setRows(pairs.map((pair) => ({ pair, loading: true })));
      const results = await Promise.all(pairs.map(async (pair): Promise<PairRow> => {
        try { return { pair, analysis: await bwtsApi.cryptoAnalysis(pair), loading: false }; }
        catch (error: any) { return { pair, loading: false, error: error?.message || 'V2 analysis failed' }; }
      }));
      setRows(results.sort((a, b) => planRank(b.analysis)-planRank(a.analysis) || (b.analysis?.total_score || 0)-(a.analysis?.total_score || 0) || (b.analysis?.trade_plan?.net_available_rr ?? b.analysis?.trade_plan?.available_rr ?? 0)-(a.analysis?.trade_plan?.net_available_rr ?? a.analysis?.trade_plan?.available_rr ?? 0))); setLastUpdate(new Date());
    } catch (error: any) { setGlobalError(error?.message || 'Failed to load tracked markets'); } finally { refreshInFlight.current = false; setRefreshing(false); }
  };
  useEffect(() => { refresh(); const id = setInterval(refresh, 60_000); return () => clearInterval(id); }, []);
  const runValidation = async () => { setValidating(true); try { setValidation(await bwtsApi.v2Backtest('BTCUSD', validationTimeframe, validationDepth)); } catch (error: any) { setGlobalError(error?.message || 'Validation replay failed'); } finally { setValidating(false); } };
  const loaded = useMemo(() => rows.filter((row) => row.analysis), [rows]);
  const eligible = loaded.filter((row) => row.analysis?.trade_plan?.eligible).length;
  const average = loaded.length ? Math.round(loaded.reduce((sum, row) => sum + (row.analysis?.total_score || 0), 0) / loaded.length) : 0;
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[24px] border border-violet-400/15 bg-[#090d18] bg-gradient-to-br from-violet-500/10 to-cyan-500/[0.04] p-6">
      <div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-[10px] font-black tracking-[0.22em] text-cyan-300">V2 MARKET INTELLIGENCE</div><h1 className="mt-2 flex items-center gap-3 text-3xl font-black text-white"><Activity className="h-7 w-7 text-cyan-300"/>Live Scanner</h1><p className="mt-2 text-sm text-slate-400">One engine for score, direction, movement and trade eligibility.{lastUpdate && <span className="ml-2 text-xs text-slate-600">Updated {lastUpdate.toLocaleTimeString()}</span>}</p></div><div className="flex items-center gap-2"><select value={validationTimeframe} onChange={(event) => setValidationTimeframe(event.target.value)} disabled={validating} className="rounded-lg border border-white/10 bg-black/20 px-2 py-2 text-xs text-slate-300"><option value="15m">15m</option><option value="1h">1h</option><option value="4h">4h</option></select><select value={validationDepth} onChange={(event) => setValidationDepth(Number(event.target.value))} disabled={validating} className="rounded-lg border border-white/10 bg-black/20 px-2 py-2 text-xs text-slate-300"><option value={5000}>5K bars</option><option value={10000}>10K bars</option><option value={20000}>20K bars</option></select><button onClick={runValidation} disabled={validating} className="flex items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-400/10 px-4 py-2.5 text-xs font-black text-violet-200 transition hover:bg-violet-400/15 disabled:opacity-50"><FlaskConical className={`h-4 w-4 ${validating ? 'animate-pulse' : ''}`}/>{validating ? `Replaying ${validationDepth.toLocaleString()} bars` : 'Run validation'}</button><button onClick={() => { bwtsApi.clearCache(); refresh(); }} disabled={refreshing} className="flex items-center gap-2 rounded-xl border border-cyan-400/20 bg-cyan-400/10 px-4 py-2.5 text-xs font-black text-cyan-200 transition hover:bg-cyan-400/15 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${refreshing ? 'animate-spin' : ''}`}/>Refresh V2</button></div></div>
      <div className="mt-6 grid grid-cols-3 gap-3"><Metric label="MARKETS" value={String(rows.length)}/><Metric label="ELIGIBLE PLANS" value={String(eligible)}/><Metric label="AVERAGE SCORE" value={`${average}/100`}/></div>
    </section>
    {globalError && <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-rose-300">{globalError}</div>}
    {validation && <section className="rounded-[20px] border border-violet-400/15 bg-[#090d18] p-5"><div className="flex items-center justify-between"><div><div className="text-[9px] font-black tracking-[0.2em] text-violet-300">WALK-FORWARD VALIDATION · {validation.pair} {validation.timeframe} · {validation.history?.years.toFixed(1) || '0.0'} YEARS</div><h2 className="mt-1 text-lg font-black">Out-of-sample evidence</h2></div><span className={`rounded-md px-2 py-1 text-[9px] font-black ${validation.validation.status === 'PROMISING' ? 'bg-emerald-400/10 text-emerald-300' : validation.validation.status === 'REJECT' ? 'bg-rose-400/10 text-rose-300' : 'bg-amber-400/10 text-amber-300'}`}>{validation.validation.status.replace(/_/g, ' ')}</span></div><div className="mt-4 grid grid-cols-4 gap-3"><Metric label="TRADES" value={String(validation.overall.trades)}/><Metric label="WIN RATE" value={`${(validation.overall.win_rate*100).toFixed(1)}%`}/><Metric label="EXPECTANCY" value={`${validation.overall.expectancy_r.toFixed(2)}R`}/><Metric label="OOS TRADES" value={String(validation.validation.observed_out_of_sample_trades)}/></div><p className="mt-3 text-[10px] text-slate-500">{validation.validation.warning}</p></section>}
    <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">{rows.map((row) => <PairCard key={row.pair} row={row}/>)}{rows.length === 0 && !globalError && <div className="col-span-full py-12 text-center text-slate-500">{refreshing ? 'Loading V2 analysis…' : 'No markets configured.'}</div>}</div>
  </div>;
};
const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-xl border border-white/[0.06] bg-black/20 p-3"><div className="text-[9px] font-black tracking-widest text-slate-500">{label}</div><div className="mt-1 text-xl font-black text-white">{value}</div></div>;
const Point = ({ label, value }: { label: string; value: number | null | undefined }) => <div className="rounded-lg bg-black/20 p-2"><div className="text-[8px] font-black tracking-widest text-slate-600">{label}</div><div className="mt-1 font-mono text-xs text-slate-300">{value == null ? 'WAIT' : value.toLocaleString(undefined, { maximumFractionDigits: 5 })}</div></div>;
const PairCard: React.FC<{ row: PairRow }> = ({ row }) => {
  if (row.loading) return <div className="h-72 animate-pulse rounded-[20px] border border-white/[0.06] bg-[#090d18]"/>;
  if (row.error || !row.analysis) return <div className="rounded-[20px] border border-white/[0.06] bg-[#090d18] p-5"><div className="flex justify-between"><h3 className="text-lg font-black">{row.pair}</h3><span className="text-xs text-slate-600">NO DATA</span></div><p className="mt-2 text-sm text-slate-500">{row.error || 'No V2 analysis available.'}</p></div>;
  const analysis = row.analysis; const plan = analysis.trade_plan; const Icon = analysis.direction === 'BUY' ? TrendingUp : analysis.direction === 'SELL' ? TrendingDown : Activity;
  const caps: Record<string, number> = { structure: 20, liquidity: 15, volume: 10, momentum: 10, moving_averages: 10, fibonacci: 10, patterns: 10, volatility: 10, relative_strength: 5 };
  const topCategories = Object.entries(analysis.category_breakdown).sort((a, b) => b[1] - a[1]).slice(0, 3);
  const timingReasons = analysis.trade_timing?.status === 'AVOID' ? analysis.trade_timing.avoid_reasons || [] : analysis.trade_timing?.wait_for || [];
  const additionalPlanReason = plan?.reasons?.find((reason) => !reason.startsWith('Trade timing'));
  return <article className="rounded-[20px] border border-white/[0.08] bg-[#090d18] p-5 transition hover:border-cyan-400/20">
    <div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-black text-white">{row.pair}</h2><span className={`rounded-md border px-2 py-1 text-[9px] font-black ${planStyle[plan?.status || 'WAIT']}`}>{plan?.status || 'WAIT'}</span>{analysis.direction_stability && <span title={analysis.direction_stability.reason} className="rounded-md bg-white/[0.05] px-2 py-1 text-[9px] font-black text-slate-300">{analysis.direction_stability.lifecycle}{analysis.direction_stability.raw_direction !== analysis.direction_stability.confirmed_direction ? ` · RAW ${analysis.direction_stability.raw_direction}` : ''}</span>}</div><div className="mt-1 text-xs capitalize text-slate-500">{analysis.scenarios.primary}</div></div><div className="text-right"><div className="text-3xl font-black text-cyan-300">{analysis.total_score}<span className="text-xs text-cyan-700">/100</span></div><div className={`mt-1 flex items-center justify-end gap-1 text-xs font-black ${analysis.direction === 'BUY' ? 'text-emerald-300' : analysis.direction === 'SELL' ? 'text-rose-300' : 'text-slate-500'}`}><Icon className="h-3.5 w-3.5"/>{analysis.direction}</div></div></div>
    <div className="mt-4 grid grid-cols-3 gap-2">{topCategories.map(([name, value]) => <div key={name} className="rounded-lg border border-white/[0.05] bg-white/[0.025] p-2"><div className="truncate text-[8px] font-black uppercase tracking-wider text-slate-600">{name.replace('_',' ')}</div><div className="mt-1 text-xs font-black text-slate-300">{value}/{caps[name] || 10}</div></div>)}</div>
    {analysis.market_context && <div className="mt-3 flex items-center justify-between rounded-lg bg-black/20 px-3 py-2 text-[9px] font-bold uppercase tracking-wider text-slate-500"><span>Month <b className="text-slate-200">{analysis.market_context.timeframes.mn1?.trend || 'neutral'}</b></span><span>Week <b className="text-slate-200">{analysis.market_context.timeframes.w1?.trend || 'neutral'}</b></span><span>Alignment <b className="text-slate-200">{analysis.market_context.alignment_score}%</b></span><span className={analysis.trade_timing?.status === 'READY' ? 'text-emerald-300' : analysis.trade_timing?.status === 'AVOID' ? 'text-rose-300' : 'text-amber-300'}>Timing {analysis.trade_timing?.status || 'WAIT'}</span></div>}
    {plan?.eligible ? <><div className="mt-4 grid grid-cols-3 gap-2"><Point label="ENTRY" value={plan.entry}/><Point label="STOP" value={plan.stop}/><Point label="TP1" value={plan.targets[0]?.price}/></div><div className="mt-3 flex justify-between text-[10px] text-slate-500"><span>Net movement {(plan.net_available_rr ?? plan.available_rr).toFixed(2)}R</span><span>Price risk {plan.risk_percent_of_price?.toFixed(2)}%</span><span>Account risk {plan.account_risk_percent.toFixed(2)}%</span></div></> : <div className="mt-4 flex gap-2 rounded-xl border border-amber-400/15 bg-amber-400/[0.06] p-3 text-xs leading-relaxed text-amber-200"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0"/><div><div>{additionalPlanReason || (analysis.trade_timing?.status === 'AVOID' ? 'Hard risk gate blocked this setup.' : 'Waiting for all required confirmations.')}</div>{timingReasons.length > 0 && <div className="mt-2 flex flex-wrap gap-1">{timingReasons.slice(0,3).map((reason) => <span key={reason} className="rounded bg-black/20 px-1.5 py-0.5 text-[9px] text-amber-300/70">{reason.replace(/_/g,' ')}</span>)}</div>}</div></div>}
    <div className="mt-4 flex items-center justify-between border-t border-white/[0.06] pt-3"><div className="flex items-center gap-2 text-[10px] text-slate-600"><CalendarClock className="h-3.5 w-3.5"/>Calendar {plan?.calendar_status || analysis.economic_calendar?.status || 'UNAVAILABLE'}</div><Link to="/tradingview" className="flex items-center gap-1 text-xs font-black text-cyan-300 hover:text-cyan-200">Validate chart <ArrowRight className="h-3.5 w-3.5"/></Link></div>
  </article>;
};
export default LiveScanner;
